<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FieldRequirementSeeder extends Seeder
{
    public function run(): void
    {
        $artFieldIds = DB::table('art_fields')->pluck('id', 'name');

        $countries = [
            'ایران', 'آلمان', 'فرانسه', 'ژاپن', 'ایالات متحده', 'کانادا', 'استرالیا'
        ];

        $citiesByCountry = [
            'ایران' => ['تهران', 'اصفهان', 'شیراز', 'تبریز', 'مشهد', 'رشت', 'اهواز'],
            'آلمان' => ['برلین', 'مونیخ', 'هامبورگ', 'کلن'],
            'فرانسه' => ['پاریس', 'لیون', 'مارسی', 'لیل'],
            'ژاپن' => ['توکیو', 'اوزاکا', 'کیوتو', 'یوکوهاما'],
            'ایالات متحده' => ['نیویورک', 'لس‌آنجلس', 'شیکاگو', 'سان‌فرانسیسکو'],
            'کانادا' => ['تورنتو', 'ونکوور', 'مونترآل', 'اتاوا'],
            'استرالیا' => ['سیدنی', 'ملبورن', 'بریزبین', 'ادلیید'],
        ];

        $sharedFields = [
            [
                'field_name' => 'artist_statement',
                'display_name' => 'سخن هنرمند',
                'display_name_en' => 'Artist Statement',
                'requirement_type' => 'required',
                'field_type' => 'textarea',
                'description' => 'لطفاً اندیشه‌ها، انگیزه‌ها و هدف خود از خلق اثر را در حداکثر ۳۵۰ کلمه بیان کنید.',
                'description_en' => 'Describe your inspirations, intentions, and objectives for the work (max 350 words).',
                'validation_rules' => ['max_length' => 2000, 'rows' => 6],
                'order' => 800,
            ],
            [
                'field_name' => 'country',
                'display_name' => 'کشور محل زندگی',
                'display_name_en' => 'Country of Residence',
                'requirement_type' => 'optional',
                'field_type' => 'select',
                'description' => 'کشوری که هم‌اکنون در آن سکونت دارید.',
                'description_en' => 'Where you currently live.',
                'validation_rules' => ['options' => $countries],
                'order' => 810,
            ],
            [
                'field_name' => 'city',
                'display_name' => 'شهر',
                'display_name_en' => 'City',
                'requirement_type' => 'optional',
                'field_type' => 'select',
                'description' => 'پس از انتخاب کشور، شهر محل زندگی خود را انتخاب کنید.',
                'description_en' => 'Select your city after choosing the country.',
                'validation_rules' => [
                    'dependent_on' => 'country',
                    'options_by_country' => $citiesByCountry,
                ],
                'order' => 820,
            ],
            [
                'field_name' => 'short_resume',
                'display_name' => 'رزومه کوتاه',
                'display_name_en' => 'Short Résumé',
                'requirement_type' => 'optional',
                'field_type' => 'textarea',
                'description' => 'سوابق هنری و تحصیلی خود را در حداکثر ۱۵۰ کلمه بنویسید.',
                'description_en' => 'Summarise your artistic background (max 150 words).',
                'validation_rules' => ['max_length' => 1200, 'rows' => 4],
                'order' => 830,
            ],
        ];

        $fieldRequirements = [
            'نقاشی' => [
                [
                    'field_name' => 'title',
                    'display_name' => 'نام اثر',
                    'display_name_en' => 'Title',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'عنوان رسمی اثری که ارسال می‌کنید.',
                    'description_en' => 'Official title of the submitted work.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 10,
                ],
                [
                    'field_name' => 'artist_name',
                    'display_name' => 'نام هنرمند',
                    'display_name_en' => 'Artist Name',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام کامل هنرمندی که اثر را خلق کرده است.',
                    'description_en' => 'Full name of the artist.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 20,
                ],
                [
                    'field_name' => 'dimensions',
                    'display_name' => 'ابعاد اثر (طول × عرض)',
                    'display_name_en' => 'Dimensions (H × W)',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'ابعاد اثر را به سانتی‌متر وارد کنید.',
                    'description_en' => 'Provide the height and width in centimetres.',
                    'validation_rules' => ['max_length' => 100],
                    'order' => 30,
                ],
                [
                    'field_name' => 'materials',
                    'display_name' => 'مواد به کار رفته',
                    'display_name_en' => 'Materials',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'مواد و تکنیک مورد استفاده برای خلق اثر.',
                    'description_en' => 'Materials and techniques used.',
                    'validation_rules' => ['max_length' => 255],
                    'order' => 40,
                ],
                [
                    'field_name' => 'main_image',
                    'display_name' => 'عکس اصلی اثر',
                    'display_name_en' => 'Main Image',
                    'requirement_type' => 'required',
                    'field_type' => 'image',
                    'description' => 'تصویر با کیفیت از نمای اصلی اثر.',
                    'description_en' => 'High-quality frontal photograph of the work.',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 15360,
                    ],
                    'order' => 50,
                ],
                [
                    'field_name' => 'detail_images',
                    'display_name' => 'عکس‌های جزئیات',
                    'display_name_en' => 'Detail Images',
                    'requirement_type' => 'required',
                    'field_type' => 'image',
                    'description' => 'از ۱ تا ۸ عکس از جزئیات یا بافت‌های اثر ارسال کنید.',
                    'description_en' => 'Submit 1–8 close-up or detail shots.',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 8192,
                        'allow_multiple' => true,
                        'min_items' => 1,
                        'max_items' => 8,
                    ],
                    'order' => 60,
                ],
                [
                    'field_name' => 'sketch_images',
                    'display_name' => 'طرح‌ها یا اسکیس‌ها',
                    'display_name_en' => 'Sketches / Process',
                    'requirement_type' => 'optional',
                    'field_type' => 'image',
                    'description' => 'مراحل شکل‌گیری اثر (حداکثر ۸ تصویر).',
                    'description_en' => 'Process sketches or studies (up to 8 images).',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 5120,
                        'allow_multiple' => true,
                        'max_items' => 8,
                    ],
                    'order' => 70,
                ],
            ],
            'معماری' => [
                [
                    'field_name' => 'title',
                    'display_name' => 'عنوان پروژه',
                    'display_name_en' => 'Project Title',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'عنوان طرح معماری خود را وارد کنید.',
                    'description_en' => 'Enter the project title.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 10,
                ],
                [
                    'field_name' => 'designer_name',
                    'display_name' => 'نام معمار/طراح',
                    'display_name_en' => 'Designer Name',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام کامل معمار یا تیم طراحی.',
                    'description_en' => 'Full name of the architect or design team.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 20,
                ],
                [
                    'field_name' => 'project_location',
                    'display_name' => 'موقعیت مکانی پروژه',
                    'display_name_en' => 'Project Location',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'در صورت فرضی بودن ذکر شود.',
                    'description_en' => 'Specify the site; indicate if hypothetical.',
                    'validation_rules' => ['max_length' => 255],
                    'order' => 30,
                ],
                [
                    'field_name' => 'project_scale',
                    'display_name' => 'اندازه تقریبی',
                    'display_name_en' => 'Approximate Scale',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'ابعاد یا مقیاس پروژه.',
                    'description_en' => 'Provide the approximate size or scale.',
                    'validation_rules' => ['max_length' => 120],
                    'order' => 40,
                ],
                [
                    'field_name' => 'main_panel',
                    'display_name' => 'پنل اصلی',
                    'display_name_en' => 'Primary Board',
                    'requirement_type' => 'required',
                    'field_type' => 'image',
                    'description' => 'پنل اصلی ارائه را با کیفیت بالا ارسال کنید.',
                    'description_en' => 'High-resolution main presentation board.',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 15360,
                    ],
                    'order' => 50,
                ],
                [
                    'field_name' => 'supporting_panels',
                    'display_name' => 'مدارک تکمیلی',
                    'display_name_en' => 'Supporting Panels',
                    'requirement_type' => 'optional',
                    'field_type' => 'image',
                    'description' => 'پلان‌ها، نماها، مقاطع یا رندرها (تا ۸ فایل).',
                    'description_en' => 'Additional boards: plans, sections, renders (up to 8).',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 15360,
                        'allow_multiple' => true,
                        'max_items' => 8,
                    ],
                    'order' => 60,
                ],
                [
                    'field_name' => 'concept_description',
                    'display_name' => 'شرح طرح و کانسپت',
                    'display_name_en' => 'Concept Narrative',
                    'requirement_type' => 'optional',
                    'field_type' => 'textarea',
                    'description' => 'در صورت نیاز توضیحات بیشتر ارائه دهید (حداکثر ۲ صفحه).',
                    'description_en' => 'Extended concept narrative (PDF, up to 2 pages).',
                    'validation_rules' => ['max_length' => 3000, 'rows' => 6],
                    'order' => 70,
                ],
                [
                    'field_name' => 'model_media',
                    'display_name' => 'مدارک ماکت / رسانه',
                    'display_name_en' => 'Model Media',
                    'requirement_type' => 'optional',
                    'field_type' => 'file',
                    'description' => 'تصاویر یا ویدئو کوتاه از ماکت یا تجربه فیزیکی.',
                    'description_en' => 'Images or short video showcasing the physical model or experience.',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png', 'mp4', 'mov'],
                        'max_size' => 153600,
                        'allow_multiple' => true,
                        'max_items' => 8,
                    ],
                    'order' => 80,
                ],
            ],
            'موسیقی' => [
                [
                    'field_name' => 'title',
                    'display_name' => 'نام اثر',
                    'display_name_en' => 'Title',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'عنوان قطعه موسیقی یا اجرا.',
                    'description_en' => 'Title of the composition or performance.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 10,
                ],
                [
                    'field_name' => 'creator_name',
                    'display_name' => 'نام آهنگساز/نوازنده',
                    'display_name_en' => 'Composer / Performer',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام خالق اثر موسیقایی را وارد کنید.',
                    'description_en' => 'Enter the composer or lead performer.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 20,
                ],
                [
                    'field_name' => 'music_subcategory',
                    'display_name' => 'گرایش موسیقی',
                    'display_name_en' => 'Music Category',
                    'requirement_type' => 'required',
                    'field_type' => 'select',
                    'description' => 'گرایش اثر خود را انتخاب کنید.',
                    'description_en' => 'Choose whether the work is a composition or performance.',
                    'validation_rules' => ['options' => ['آهنگسازی', 'نوازندگی']],
                    'order' => 30,
                ],
                [
                    'field_name' => 'idea_description',
                    'display_name' => 'طرح و ایده اولیه',
                    'display_name_en' => 'Concept Statement',
                    'requirement_type' => 'required',
                    'field_type' => 'textarea',
                    'description' => 'ارتباط اثر با جشنواره و شرح ایده را توضیح دهید.',
                    'description_en' => 'Explain how the work connects to the festival’s theme.',
                    'validation_rules' => ['max_length' => 2000, 'rows' => 5],
                    'order' => 40,
                ],
                [
                    'field_name' => 'primary_media',
                    'display_name' => 'فایل اصلی اثر',
                    'display_name_en' => 'Primary Media',
                    'requirement_type' => 'required',
                    'field_type' => 'file',
                    'description' => 'برای آهنگسازی فایل صوتی و برای نوازندگی فایل ویدئویی ارسال کنید.',
                    'description_en' => 'Upload the main audio (composition) or video (performance).',
                    'validation_rules' => [
                        'allowed_formats' => ['wav', 'mp3', 'mp4', 'mov'],
                        'max_size' => 512000,
                    ],
                    'order' => 50,
                ],
                [
                    'field_name' => 'score_file',
                    'display_name' => 'پارتیتور',
                    'display_name_en' => 'Score (PDF)',
                    'requirement_type' => 'optional',
                    'field_type' => 'file',
                    'description' => 'پارتیتور یا نت کامل اثر (در صورت وجود).',
                    'description_en' => 'Full score in PDF format (if applicable).',
                    'validation_rules' => [
                        'allowed_formats' => ['pdf'],
                        'max_size' => 20480,
                    ],
                    'order' => 60,
                ],
                [
                    'field_name' => 'performer_names',
                    'display_name' => 'نام نوازندگان و سازها',
                    'display_name_en' => 'Performers & Instrumentation',
                    'requirement_type' => 'optional',
                    'field_type' => 'text',
                    'description' => 'در صورت اجرا، نام نوازندگان و سازهای مورد استفاده را وارد کنید.',
                    'description_en' => 'List performers and instrumentation as needed.',
                    'validation_rules' => ['max_length' => 255],
                    'order' => 70,
                ],
                [
                    'field_name' => 'poster_image',
                    'display_name' => 'پوستر اثر',
                    'display_name_en' => 'Poster',
                    'requirement_type' => 'optional',
                    'field_type' => 'image',
                    'description' => 'پوستر یا تصویر شاخص اثر (اختیاری).',
                    'description_en' => 'Optional promotional poster or cover image.',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 10240,
                    ],
                    'order' => 80,
                ],
                [
                    'field_name' => 'performance_video',
                    'display_name' => 'ویدئوی اجرا',
                    'display_name_en' => 'Performance Video',
                    'requirement_type' => 'optional',
                    'field_type' => 'file',
                    'description' => 'ویدئوی ضبط‌شده از اجرای اثر (حداکثر ۷ دقیقه).',
                    'description_en' => 'Recorded performance (up to 7 minutes).',
                    'validation_rules' => [
                        'allowed_formats' => ['mp4', 'mov'],
                        'max_size' => 307200,
                    ],
                    'order' => 90,
                ],
            ],
            'ادبیات' => [
                [
                    'field_name' => 'title',
                    'display_name' => 'نام اثر',
                    'display_name_en' => 'Title',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'عنوان شعر یا داستان کوتاه.',
                    'description_en' => 'Title of the story or poem.',
                    'validation_rules' => ['max_length' => 200],
                    'order' => 10,
                ],
                [
                    'field_name' => 'author_name',
                    'display_name' => 'نام نویسنده',
                    'display_name_en' => 'Author Name',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام کامل نویسنده یا شاعر.',
                    'description_en' => 'Full name of the author or poet.',
                    'validation_rules' => ['max_length' => 200],
                    'order' => 20,
                ],
                [
                    'field_name' => 'completion_date',
                    'display_name' => 'تاریخ اتمام نگارش',
                    'display_name_en' => 'Completion Date',
                    'requirement_type' => 'required',
                    'field_type' => 'date',
                    'description' => 'تاریخ پایان نگارش اثر.',
                    'description_en' => 'Date when the work was completed.',
                    'order' => 30,
                ],
                [
                    'field_name' => 'literature_type',
                    'display_name' => 'نوع اثر (داستان/شعر)',
                    'display_name_en' => 'Form (Story/Poem)',
                    'requirement_type' => 'required',
                    'field_type' => 'select',
                    'description' => 'نوع اثر ادبی خود را مشخص کنید.',
                    'description_en' => 'Specify whether the work is prose or poetry.',
                    'validation_rules' => ['options' => ['داستان کوتاه', 'شعر']],
                    'order' => 40,
                ],
                [
                    'field_name' => 'language',
                    'display_name' => 'زبان اثر',
                    'display_name_en' => 'Language',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'زبان اصلی اثر (در صورت ترجمه ذکر شود).',
                    'description_en' => 'Original language of the work (mention if translated).',
                    'validation_rules' => ['max_length' => 120],
                    'order' => 50,
                ],
                [
                    'field_name' => 'manuscript_file',
                    'display_name' => 'فایل اثر (PDF)',
                    'display_name_en' => 'Manuscript (PDF)',
                    'requirement_type' => 'required',
                    'field_type' => 'file',
                    'description' => 'متن کامل اثر با فرمت PDF.',
                    'description_en' => 'Full manuscript in PDF format.',
                    'validation_rules' => [
                        'allowed_formats' => ['pdf'],
                        'max_size' => 5120,
                    ],
                    'order' => 60,
                ],
                [
                    'field_name' => 'audio_file',
                    'display_name' => 'فایل صوتی خوانش اثر',
                    'display_name_en' => 'Audio Reading',
                    'requirement_type' => 'required',
                    'field_type' => 'audio',
                    'description' => 'خوانش شعر یا داستان (MP3/WAV – تا ۱۵ دقیقه).',
                    'description_en' => 'Audio recital of the work (MP3/WAV – up to 15 minutes).',
                    'validation_rules' => [
                        'allowed_formats' => ['mp3', 'wav'],
                        'max_size' => 40960,
                    ],
                    'order' => 70,
                ],
                [
                    'field_name' => 'work_summary',
                    'display_name' => 'شرح اثر / منبع الهام',
                    'display_name_en' => 'Work Summary / Inspiration',
                    'requirement_type' => 'optional',
                    'field_type' => 'textarea',
                    'description' => 'درباره منبع الهام یا مفهوم اثر توضیح دهید.',
                    'description_en' => 'Optional note about inspiration or context (up to 200 words).',
                    'validation_rules' => ['max_length' => 1500, 'rows' => 4],
                    'order' => 80,
                ],
                [
                    'field_name' => 'visual_assets',
                    'display_name' => 'تصاویر همراه',
                    'display_name_en' => 'Supporting Images',
                    'requirement_type' => 'optional',
                    'field_type' => 'image',
                    'description' => 'تصویرسازی یا عکس‌های مرتبط (۱ تا ۸ تصویر).',
                    'description_en' => 'Related illustrations or photography (1–8 images).',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 15360,
                        'allow_multiple' => true,
                        'max_items' => 8,
                    ],
                    'order' => 90,
                ],
                [
                    'field_name' => 'recitation_video',
                    'display_name' => 'ویدئوی خوانش اثر',
                    'display_name_en' => 'Reading Video',
                    'requirement_type' => 'optional',
                    'field_type' => 'video',
                    'description' => 'ویدئوی خوانش شعر یا داستان (اختیاری).',
                    'description_en' => 'Optional video of the work being read.',
                    'validation_rules' => [
                        'allowed_formats' => ['mp4', 'mov'],
                        'max_size' => 307200,
                    ],
                    'order' => 95,
                ],
            ],
            'عکاسی' => [
                [
                    'field_name' => 'submission_type',
                    'display_name' => 'نوع ارسال',
                    'display_name_en' => 'Submission Type',
                    'requirement_type' => 'required',
                    'field_type' => 'select',
                    'description' => 'مشخص کنید اثر شما تک عکس است یا مجموعه.',
                    'description_en' => 'Indicate whether you are submitting a single image or a series.',
                    'validation_rules' => ['options' => ['تک عکس', 'مجموعه']],
                    'order' => 10,
                ],
                [
                    'field_name' => 'title',
                    'display_name' => 'نام اثر / مجموعه',
                    'display_name_en' => 'Title / Series Name',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'عنوان عکس یا مجموعه را وارد کنید.',
                    'description_en' => 'Provide the title for the image or series.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 20,
                ],
                [
                    'field_name' => 'photographer_name',
                    'display_name' => 'نام عکاس',
                    'display_name_en' => 'Photographer Name',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام کامل عکاس را وارد کنید.',
                    'description_en' => 'Full name of the photographer.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 30,
                ],
                [
                    'field_name' => 'shoot_datetime',
                    'display_name' => 'تاریخ و زمان عکاسی',
                    'display_name_en' => 'Date & Time of Capture',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'روز، ماه، سال و در صورت امکان ساعت عکاسی.',
                    'description_en' => 'Specify day, month, year, and optionally time of capture.',
                    'validation_rules' => ['max_length' => 120],
                    'order' => 40,
                ],
                [
                    'field_name' => 'shoot_location',
                    'display_name' => 'محل عکاسی',
                    'display_name_en' => 'Location',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'محل ثبت تصویر را ذکر کنید.',
                    'description_en' => 'Where the photograph was captured.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 50,
                ],
                [
                    'field_name' => 'photo_files',
                    'display_name' => 'فایل‌های عکس',
                    'display_name_en' => 'Photo Files',
                    'requirement_type' => 'required',
                    'field_type' => 'image',
                    'description' => 'برای تک عکس یک فایل و برای مجموعه تا ۱۶ تصویر ارسال کنید.',
                    'description_en' => 'Upload the single image or up to 16 photos for a series.',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 20480,
                        'allow_multiple' => true,
                        'min_items' => 1,
                        'max_items' => 16,
                    ],
                    'order' => 60,
                ],
                [
                    'field_name' => 'additional_series',
                    'display_name' => 'سری عکس اضافی',
                    'display_name_en' => 'Additional Images',
                    'requirement_type' => 'optional',
                    'field_type' => 'image',
                    'description' => 'در صورت تمایل تصاویر مکمل ارسال کنید.',
                    'description_en' => 'Optional supplementary images (up to 8).',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 20480,
                        'allow_multiple' => true,
                        'max_items' => 8,
                    ],
                    'order' => 70,
                ],
            ],
            'گرافیک و تصویرسازی' => [
                [
                    'field_name' => 'title',
                    'display_name' => 'نام اثر',
                    'display_name_en' => 'Title',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'عنوان پروژه گرافیکی یا تصویرسازی.',
                    'description_en' => 'Title of the graphic design or illustration project.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 10,
                ],
                [
                    'field_name' => 'artist_name',
                    'display_name' => 'نام هنرمند',
                    'display_name_en' => 'Artist Name',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام کامل هنرمند.',
                    'description_en' => 'Full name of the artist.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 20,
                ],
                [
                    'field_name' => 'graphic_subcategory',
                    'display_name' => 'زیرشاخه',
                    'display_name_en' => 'Subcategory',
                    'requirement_type' => 'required',
                    'field_type' => 'select',
                    'description' => 'شاخه مرتبط با اثر را انتخاب کنید.',
                    'description_en' => 'Choose the relevant category.',
                    'validation_rules' => [
                        'options' => ['طراحی پوستر', 'تصویرسازی', 'طراحی نشانه', 'اینفوگرافیک', 'طراحی جلد کتاب', 'طراحی بسته‌بندی'],
                    ],
                    'order' => 30,
                ],
                [
                    'field_name' => 'software_used',
                    'display_name' => 'نرم‌افزارهای مورد استفاده',
                    'display_name_en' => 'Software Used',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'ابزارها و نرم‌افزارهای اصلی پروژه.',
                    'description_en' => 'List the main software/tools used.',
                    'validation_rules' => ['max_length' => 255],
                    'order' => 40,
                ],
                [
                    'field_name' => 'main_file',
                    'display_name' => 'فایل اصلی اثر',
                    'display_name_en' => 'Main File',
                    'requirement_type' => 'required',
                    'field_type' => 'file',
                    'description' => 'فایل نهایی اثر (تصویر یا ویدئو برای اینفوگرافیک متحرک).',
                    'description_en' => 'Final deliverable (image or motion file for animations).',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png', 'mp4', 'mov'],
                        'max_size' => 307200,
                    ],
                    'order' => 50,
                ],
                [
                    'field_name' => 'additional_files',
                    'display_name' => 'فایل‌های تکمیلی',
                    'display_name_en' => 'Supporting Files',
                    'requirement_type' => 'optional',
                    'field_type' => 'file',
                    'description' => 'نمایش جزئیات یا نسخه‌های دیگر اثر (تا ۸ فایل).',
                    'description_en' => 'Additional visuals or versions (up to 8 files).',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png', 'mp4', 'mov'],
                        'max_size' => 307200,
                        'allow_multiple' => true,
                        'max_items' => 8,
                    ],
                    'order' => 60,
                ],
                [
                    'field_name' => 'process_files',
                    'display_name' => 'مراحل طراحی',
                    'display_name_en' => 'Process Files',
                    'requirement_type' => 'optional',
                    'field_type' => 'file',
                    'description' => 'تصاویر یا فایل‌های مربوط به روند طراحی (تا ۸ فایل).',
                    'description_en' => 'Optional process documentation (up to 8 files).',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png', 'pdf'],
                        'max_size' => 10240,
                        'allow_multiple' => true,
                        'max_items' => 8,
                    ],
                    'order' => 70,
                ],
                [
                    'field_name' => 'color_palette',
                    'display_name' => 'پالت رنگی',
                    'display_name_en' => 'Colour Palette',
                    'requirement_type' => 'optional',
                    'field_type' => 'file',
                    'description' => 'پالت رنگی اثر (اختیاری).',
                    'description_en' => 'Optional colour palette reference.',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png', 'pdf'],
                        'max_size' => 5120,
                    ],
                    'order' => 80,
                ],
            ],
            'مجسمه‌سازی' => [
                [
                    'field_name' => 'title',
                    'display_name' => 'عنوان اثر',
                    'display_name_en' => 'Title',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام کامل اثر حجمی.',
                    'description_en' => 'Title of the sculptural work.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 10,
                ],
                [
                    'field_name' => 'artist_name',
                    'display_name' => 'نام هنرمند',
                    'display_name_en' => 'Artist Name',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام کامل هنرمند.',
                    'description_en' => 'Full name of the artist.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 20,
                ],
                [
                    'field_name' => 'materials',
                    'display_name' => 'مواد به‌کاررفته',
                    'display_name_en' => 'Materials',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'مواد اولیه و تکنیک ساخت اثر.',
                    'description_en' => 'Materials and techniques used.',
                    'validation_rules' => ['max_length' => 255],
                    'order' => 30,
                ],
                [
                    'field_name' => 'dimensions',
                    'display_name' => 'ابعاد اثر (ارتفاع × عرض × طول)',
                    'display_name_en' => 'Dimensions (H × W × D)',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'ابعاد را بر حسب سانتی‌متر وارد کنید.',
                    'description_en' => 'Provide the height, width, and depth in centimetres.',
                    'validation_rules' => ['max_length' => 120],
                    'order' => 40,
                ],
                [
                    'field_name' => 'main_image',
                    'display_name' => 'عکس اصلی',
                    'display_name_en' => 'Main Photo',
                    'requirement_type' => 'required',
                    'field_type' => 'image',
                    'description' => 'تصویر اصلی اثر با پس‌زمینه ساده.',
                    'description_en' => 'Primary photo of the sculpture on a clean background.',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 15360,
                    ],
                    'order' => 50,
                ],
                [
                    'field_name' => 'view_images',
                    'display_name' => 'تصاویر زوایای مختلف',
                    'display_name_en' => 'Multiple Views',
                    'requirement_type' => 'required',
                    'field_type' => 'image',
                    'description' => 'حداقل چهار عکس از زوایای مختلف ارسال کنید.',
                    'description_en' => 'At least four images from different angles.',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 15360,
                        'allow_multiple' => true,
                        'min_items' => 4,
                        'max_items' => 8,
                    ],
                    'order' => 60,
                ],
                [
                    'field_name' => 'detail_images',
                    'display_name' => 'تصاویر جزئیات',
                    'display_name_en' => 'Detail Photos',
                    'requirement_type' => 'required',
                    'field_type' => 'image',
                    'description' => 'حداقل سه عکس از جزئیات مهم اثر ارائه کنید.',
                    'description_en' => 'Minimum three close-up detail shots.',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 10240,
                        'allow_multiple' => true,
                        'min_items' => 3,
                        'max_items' => 8,
                    ],
                    'order' => 70,
                ],
                [
                    'field_name' => 'effect_video',
                    'display_name' => 'ویدئوی کوتاه از اثر',
                    'display_name_en' => 'Short Video',
                    'requirement_type' => 'optional',
                    'field_type' => 'video',
                    'description' => 'فیلمی کوتاه (حداکثر ۴۰ ثانیه) از اثر ارسال کنید.',
                    'description_en' => 'Optional 40-second video showing the work.',
                    'validation_rules' => [
                        'allowed_formats' => ['mp4', 'mov'],
                        'max_size' => 102400,
                    ],
                    'order' => 80,
                ],
                [
                    'field_name' => 'weight',
                    'display_name' => 'وزن تقریبی',
                    'display_name_en' => 'Approximate Weight',
                    'requirement_type' => 'optional',
                    'field_type' => 'text',
                    'description' => 'وزن تقریبی اثر (در صورت امکان).',
                    'description_en' => 'Approximate weight of the work (if available).',
                    'validation_rules' => ['max_length' => 50],
                    'order' => 90,
                ],
            ],
            'خوشنویسی' => [
                [
                    'field_name' => 'title',
                    'display_name' => 'نام اثر',
                    'display_name_en' => 'Title',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'عنوان تابلو خوشنویسی.',
                    'description_en' => 'Title of the calligraphy piece.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 10,
                ],
                [
                    'field_name' => 'artist_name',
                    'display_name' => 'نام هنرمند',
                    'display_name_en' => 'Artist Name',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام خوشنویس.',
                    'description_en' => 'Full name of the calligrapher.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 20,
                ],
                [
                    'field_name' => 'calligraphy_style',
                    'display_name' => 'سبک خوشنویسی',
                    'display_name_en' => 'Calligraphy Style',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام سبک یا خطی که استفاده شده است.',
                    'description_en' => 'Name of the script or style used.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 30,
                ],
                [
                    'field_name' => 'text_content',
                    'display_name' => 'متن خوشنویسی',
                    'display_name_en' => 'Calligraphed Text',
                    'requirement_type' => 'optional',
                    'field_type' => 'file',
                    'description' => 'فایل PDF متن خوشنویسی (در صورت تمایل).',
                    'description_en' => 'PDF of the written text (optional).',
                    'validation_rules' => [
                        'allowed_formats' => ['pdf'],
                        'max_size' => 5120,
                    ],
                    'order' => 40,
                ],
                [
                    'field_name' => 'dimensions',
                    'display_name' => 'ابعاد اثر',
                    'display_name_en' => 'Dimensions',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'ابعاد اثر خوشنویسی را وارد کنید.',
                    'description_en' => 'Provide the dimensions of the piece.',
                    'validation_rules' => ['max_length' => 120],
                    'order' => 50,
                ],
                [
                    'field_name' => 'main_image',
                    'display_name' => 'عکس اثر',
                    'display_name_en' => 'Artwork Photo',
                    'requirement_type' => 'required',
                    'field_type' => 'image',
                    'description' => 'عکس با کیفیت از اثر خوشنویسی.',
                    'description_en' => 'High-quality photo of the work.',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 15360,
                    ],
                    'order' => 60,
                ],
                [
                    'field_name' => 'detail_images',
                    'display_name' => 'جزئیات یا مراحل اجرا',
                    'display_name_en' => 'Detail / Process Images',
                    'requirement_type' => 'optional',
                    'field_type' => 'image',
                    'description' => 'جزئیات اثر یا روند اجرا (تا ۸ تصویر).',
                    'description_en' => 'Optional detail shots or process images (up to 8).',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 15360,
                        'allow_multiple' => true,
                        'max_items' => 8,
                    ],
                    'order' => 70,
                ],
            ],
            'سینما' => [
                [
                    'field_name' => 'title',
                    'display_name' => 'نام اثر',
                    'display_name_en' => 'Title',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'عنوان فیلم کوتاه.',
                    'description_en' => 'Title of the short film.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 10,
                ],
                [
                    'field_name' => 'director_name',
                    'display_name' => 'نام کارگردان',
                    'display_name_en' => 'Director',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام کامل کارگردان.',
                    'description_en' => 'Full name of the director.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 20,
                ],
                [
                    'field_name' => 'writer_name',
                    'display_name' => 'نام نویسنده',
                    'display_name_en' => 'Writer',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام نویسنده یا فیلمنامه‌نویس.',
                    'description_en' => 'Playwright or script adapter.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 30,
                ],
                [
                    'field_name' => 'main_cast',
                    'display_name' => 'بازیگران اصلی',
                    'display_name_en' => 'Lead Cast',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام سه بازیگر اصلی را ذکر کنید.',
                    'description_en' => 'List the three principal actors.',
                    'validation_rules' => ['max_length' => 255],
                    'order' => 40,
                ],
                [
                    'field_name' => 'duration',
                    'display_name' => 'مدت زمان (دقیقه)',
                    'display_name_en' => 'Duration (minutes)',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'مدت زمان فیلم را وارد کنید.',
                    'description_en' => 'Provide the running time in minutes.',
                    'validation_rules' => ['max_length' => 20],
                    'order' => 50,
                ],
                [
                    'field_name' => 'synopsis',
                    'display_name' => 'خلاصه داستان',
                    'display_name_en' => 'Synopsis',
                    'requirement_type' => 'required',
                    'field_type' => 'textarea',
                    'description' => 'خلاصه‌ای از داستان فیلم (حداکثر ۳۰۰ کلمه).',
                    'description_en' => 'Brief synopsis (up to 300 words).',
                    'validation_rules' => ['max_length' => 1500, 'rows' => 4],
                    'order' => 60,
                ],
                [
                    'field_name' => 'film_file',
                    'display_name' => 'فایل فیلم',
                    'display_name_en' => 'Film File',
                    'requirement_type' => 'required',
                    'field_type' => 'video',
                    'description' => 'نسخه با کیفیت فیلم کوتاه.',
                    'description_en' => 'High-quality export of the short film.',
                    'validation_rules' => [
                        'allowed_formats' => ['mp4', 'mov'],
                        'max_size' => 1048576,
                    ],
                    'order' => 70,
                ],
                [
                    'field_name' => 'poster',
                    'display_name' => 'پوستر',
                    'display_name_en' => 'Poster',
                    'requirement_type' => 'required',
                    'field_type' => 'image',
                    'description' => 'پوستر رسمی یا تصویر شاخص.',
                    'description_en' => 'Official poster or key art.',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 10240,
                    ],
                    'order' => 80,
                ],
                [
                    'field_name' => 'behind_the_scenes',
                    'display_name' => 'پشت صحنه',
                    'display_name_en' => 'Backstage Photos',
                    'requirement_type' => 'optional',
                    'field_type' => 'image',
                    'description' => 'عکس‌های پشت صحنه یا تمرین (تا ۱۰ تصویر).',
                    'description_en' => 'Optional rehearsal or backstage photos (up to 10 images).',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 5120,
                        'allow_multiple' => true,
                        'max_items' => 10,
                    ],
                    'order' => 90,
                ],
            ],
            'نمایش' => [
                [
                    'field_name' => 'title',
                    'display_name' => 'نام اثر',
                    'display_name_en' => 'Title',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'عنوان اجرای نمایشی.',
                    'description_en' => 'Title of the theatrical production.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 10,
                ],
                [
                    'field_name' => 'director_name',
                    'display_name' => 'نام کارگردان',
                    'display_name_en' => 'Director',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام کامل کارگردان.',
                    'description_en' => 'Full name of the director.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 20,
                ],
                [
                    'field_name' => 'writer_name',
                    'display_name' => 'نام نویسنده',
                    'display_name_en' => 'Writer',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام نویسنده یا دراماتورژ اثر.',
                    'description_en' => 'Playwright or script adapter.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 30,
                ],
                [
                    'field_name' => 'main_cast',
                    'display_name' => 'بازیگران اصلی',
                    'display_name_en' => 'Lead Cast',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام سه بازیگر اصلی را ذکر کنید.',
                    'description_en' => 'List the three principal performers.',
                    'validation_rules' => ['max_length' => 255],
                    'order' => 40,
                ],
                [
                    'field_name' => 'duration',
                    'display_name' => 'مدت زمان اجرا',
                    'display_name_en' => 'Running Time',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'مدت اجرا را به دقیقه بنویسید.',
                    'description_en' => 'Provide the running time in minutes.',
                    'validation_rules' => ['max_length' => 20],
                    'order' => 50,
                ],
                [
                    'field_name' => 'synopsis',
                    'display_name' => 'خلاصه داستان',
                    'display_name_en' => 'Synopsis',
                    'requirement_type' => 'required',
                    'field_type' => 'textarea',
                    'description' => 'خلاصه‌ای از اجرا (حداکثر ۳۰۰ کلمه).',
                    'description_en' => 'Short synopsis (up to 300 words).',
                    'validation_rules' => ['max_length' => 1500, 'rows' => 4],
                    'order' => 60,
                ],
                [
                    'field_name' => 'performance_video',
                    'display_name' => 'فیلم اجرا',
                    'display_name_en' => 'Performance Video',
                    'requirement_type' => 'required',
                    'field_type' => 'video',
                    'description' => 'ویدئوی اجرا با کیفیت مناسب.',
                    'description_en' => 'Video capture of the performance.',
                    'validation_rules' => [
                        'allowed_formats' => ['mp4', 'mov'],
                        'max_size' => 1024000,
                    ],
                    'order' => 70,
                ],
                [
                    'field_name' => 'poster',
                    'display_name' => 'پوستر',
                    'display_name_en' => 'Poster',
                    'requirement_type' => 'required',
                    'field_type' => 'image',
                    'description' => 'پوستر یا تصویر معرفی اجرا.',
                    'description_en' => 'Official poster or promotional artwork.',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 10240,
                    ],
                    'order' => 80,
                ],
                [
                    'field_name' => 'behind_the_scenes',
                    'display_name' => 'عکس‌های پشت صحنه',
                    'display_name_en' => 'Backstage Photos',
                    'requirement_type' => 'optional',
                    'field_type' => 'image',
                    'description' => 'عکس‌های پشت صحنه یا تمرین (تا ۱۰ تصویر).',
                    'description_en' => 'Optional rehearsal or backstage photos (up to 10 images).',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 5120,
                        'allow_multiple' => true,
                        'max_items' => 10,
                    ],
                    'order' => 90,
                ],
            ],
            'انیمیشن' => [
                [
                    'field_name' => 'title',
                    'display_name' => 'نام اثر',
                    'display_name_en' => 'Title',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'عنوان انیمیشن.',
                    'description_en' => 'Title of the animation.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 10,
                ],
                [
                    'field_name' => 'director_name',
                    'display_name' => 'نام کارگردان',
                    'display_name_en' => 'Director',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام کامل کارگردان.',
                    'description_en' => 'Full name of the director.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 20,
                ],
                [
                    'field_name' => 'writer_name',
                    'display_name' => 'نام نویسنده',
                    'display_name_en' => 'Writer',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام نویسنده یا دراماتورژ.',
                    'description_en' => 'Name of the writer or story developer.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 30,
                ],
                [
                    'field_name' => 'technique',
                    'display_name' => 'تکنیک انیمیشن',
                    'display_name_en' => 'Animation Technique',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'تکنیک یا فناوری تولید اثر.',
                    'description_en' => 'Technique or technology used.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 40,
                ],
                [
                    'field_name' => 'duration',
                    'display_name' => 'مدت زمان اثر',
                    'display_name_en' => 'Duration',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'مدت انیمیشن را به دقیقه بنویسید.',
                    'description_en' => 'Running time in minutes.',
                    'validation_rules' => ['max_length' => 20],
                    'order' => 50,
                ],
                [
                    'field_name' => 'synopsis',
                    'display_name' => 'خلاصه داستان',
                    'display_name_en' => 'Synopsis',
                    'requirement_type' => 'required',
                    'field_type' => 'textarea',
                    'description' => 'خلاصه‌ای از داستان یا مفهوم (حداکثر ۲۰۰ کلمه).',
                    'description_en' => 'Short synopsis (up to 200 words).',
                    'validation_rules' => ['max_length' => 1200, 'rows' => 4],
                    'order' => 60,
                ],
                [
                    'field_name' => 'animation_file',
                    'display_name' => 'فایل انیمیشن',
                    'display_name_en' => 'Animation File',
                    'requirement_type' => 'required',
                    'field_type' => 'video',
                    'description' => 'نسخه با کیفیت انیمیشن.',
                    'description_en' => 'High-quality export of the animation.',
                    'validation_rules' => [
                        'allowed_formats' => ['mp4', 'mov'],
                        'max_size' => 512000,
                    ],
                    'order' => 70,
                ],
                [
                    'field_name' => 'poster',
                    'display_name' => 'پوستر',
                    'display_name_en' => 'Poster',
                    'requirement_type' => 'required',
                    'field_type' => 'image',
                    'description' => 'پوستر یا تصویر شاخص اثر.',
                    'description_en' => 'Key artwork or poster.',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png'],
                        'max_size' => 10240,
                    ],
                    'order' => 80,
                ],
                [
                    'field_name' => 'production_assets',
                    'display_name' => 'تصاویر مراحل تولید',
                    'display_name_en' => 'Production Assets',
                    'requirement_type' => 'optional',
                    'field_type' => 'file',
                    'description' => 'تصاویر یا اسناد تولید (تا ۱۵ فایل).',
                    'description_en' => 'Optional production stills or documents (up to 15 files).',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png', 'pdf'],
                        'max_size' => 5120,
                        'allow_multiple' => true,
                        'max_items' => 15,
                    ],
                    'order' => 90,
                ],
            ],
            'هنرهای جدید' => [
                [
                    'field_name' => 'title',
                    'display_name' => 'عنوان اثر',
                    'display_name_en' => 'Title',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'عنوان پروژه هنرهای جدید.',
                    'description_en' => 'Title of the new media project.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 10,
                ],
                [
                    'field_name' => 'artist_name',
                    'display_name' => 'نام هنرمند',
                    'display_name_en' => 'Artist Name',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نام کامل هنرمند.',
                    'description_en' => 'Full name of the artist.',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 20,
                ],
                [
                    'field_name' => 'media_type',
                    'display_name' => 'رسانه اثر',
                    'display_name_en' => 'Media Type',
                    'requirement_type' => 'required',
                    'field_type' => 'text',
                    'description' => 'نوع رسانه (دیجیتال، چیدمان، تعاملی و ...).',
                    'description_en' => 'Media type (digital, installation, interactive, etc.).',
                    'validation_rules' => ['max_length' => 150],
                    'order' => 30,
                ],
                [
                    'field_name' => 'primary_file',
                    'display_name' => 'فایل اصلی',
                    'display_name_en' => 'Primary File',
                    'requirement_type' => 'required',
                    'field_type' => 'file',
                    'description' => 'فایل اصلی اثر متناسب با رسانه.',
                    'description_en' => 'Primary file appropriate to the medium.',
                    'validation_rules' => [
                        'allowed_formats' => ['mp4', 'mov', 'jpeg', 'jpg', 'png', 'pdf'],
                        'max_size' => 512000,
                    ],
                    'order' => 40,
                ],
                [
                    'field_name' => 'secondary_files',
                    'display_name' => 'فایل‌های فرعی',
                    'display_name_en' => 'Supporting Files',
                    'requirement_type' => 'optional',
                    'field_type' => 'file',
                    'description' => 'اسناد یا مدیاهای تکمیلی (۱ تا ۸ فایل).',
                    'description_en' => 'Additional supporting media (1–8 files).',
                    'validation_rules' => [
                        'allowed_formats' => ['mp4', 'mov', 'jpeg', 'jpg', 'png', 'pdf'],
                        'max_size' => 512000,
                        'allow_multiple' => true,
                        'max_items' => 8,
                    ],
                    'order' => 50,
                ],
                [
                    'field_name' => 'sketch_files',
                    'display_name' => 'طرح‌ها یا اسناد اولیه',
                    'display_name_en' => 'Sketches / Notes',
                    'requirement_type' => 'optional',
                    'field_type' => 'file',
                    'description' => 'طرح‌های اولیه یا توضیحات فنی (۱ تا ۸ فایل).',
                    'description_en' => 'Preparatory sketches or technical notes (1–8 files).',
                    'validation_rules' => [
                        'allowed_formats' => ['jpeg', 'jpg', 'png', 'pdf'],
                        'max_size' => 20480,
                        'allow_multiple' => true,
                        'max_items' => 8,
                    ],
                    'order' => 60,
                ],
                [
                    'field_name' => 'dimensions_or_duration',
                    'display_name' => 'ابعاد / مدت زمان',
                    'display_name_en' => 'Dimensions / Duration',
                    'requirement_type' => 'optional',
                    'field_type' => 'text',
                    'description' => 'ابعاد فیزیکی یا مدت زمان اثر.',
                    'description_en' => 'Physical dimensions or duration of the work.',
                    'validation_rules' => ['max_length' => 120],
                    'order' => 70,
                ],
            ],
        ];

        foreach ($fieldRequirements as $fieldName => $requirements) {
            $artFieldId = $artFieldIds[$fieldName] ?? null;
            if (!$artFieldId) {
                continue;
            }

            DB::table('field_requirements')->where('art_field_id', $artFieldId)->delete();

            $merged = array_merge($requirements, $sharedFields);

            foreach ($merged as $requirement) {
                $payload = [
                    'art_field_id' => $artFieldId,
                    'field_name' => $requirement['field_name'],
                    'display_name' => $requirement['display_name'],
                    'display_name_en' => $requirement['display_name_en'] ?? null,
                    'requirement_type' => $requirement['requirement_type'],
                    'field_type' => $requirement['field_type'],
                    'description' => $requirement['description'] ?? null,
                    'description_en' => $requirement['description_en'] ?? null,
                    'validation_rules' => isset($requirement['validation_rules'])
                        ? json_encode($requirement['validation_rules'], JSON_UNESCAPED_UNICODE)
                        : null,
                    'order' => $requirement['order'] ?? 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ];

                DB::table('field_requirements')->updateOrInsert(
                    [
                        'art_field_id' => $artFieldId,
                        'field_name' => $requirement['field_name'],
                    ],
                    $payload
                );
            }
        }
    }
}
